name = "LTVSourceReceiverModel"
uuid = "672b6255-fadc-4b5b-918a-a202f856ec05"
authors = ["Mamta <mamta16@nmsu.edu> and contributors"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
